// Player-facing labels; production contracts live in scripts/authoring.
export const challengeBriefs = [
  {
    id: 1,
    title: ['中心来路', 'Trace the goal · 1'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'normal',
    shape: 'square',
    kind: 'normal',
    targets: 1,
    keyGroups: 0,
    target: 34,
    size: 19,
    depth: 6,
  },
  {
    id: 2,
    title: ['两处挡路', 'Trace the goal · 2'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'normal',
    shape: 'wings',
    kind: 'normal',
    targets: 1,
    keyGroups: 0,
    target: 35,
    size: 19,
    depth: 9,
  },
  {
    id: 3,
    title: ['折身直出', 'Trace the goal · 3'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'normal',
    shape: 'square',
    kind: 'mixed',
    targets: 1,
    keyGroups: 0,
    target: 33,
    size: 19,
    depth: 9,
  },
  {
    id: 4,
    title: ['一步展开', 'Trace the goal · 4'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'hard',
    shape: 'square',
    kind: 'normal',
    targets: 1,
    keyGroups: 0,
    target: 37,
    size: 19,
    depth: 6,
  },
  {
    id: 5,
    title: ['两片清空', 'Trace the goal · 5'],
    focus: [
      '看清尖端方向，移走全部箭头。',
      'Follow each tip and free every arrow.',
    ],
    tier: 'normal',
    shape: 'islands',
    kind: 'normal',
    targets: 0,
    keyGroups: 0,
    target: 35,
    size: 19,
    depth: 0,
  },
  {
    id: 6,
    title: ['出口不在边', 'Trace the goal · 6'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'normal',
    shape: 'diamond',
    kind: 'normal',
    targets: 1,
    keyGroups: 0,
    target: 33,
    size: 19,
    depth: 10,
  },
  {
    id: 7,
    title: ['留下角落', 'Trace the goal · 7'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'normal',
    shape: 'square',
    kind: 'normal',
    targets: 1,
    keyGroups: 0,
    target: 34,
    size: 19,
    depth: 9,
  },
  {
    id: 8,
    title: ['两星共根', 'Trace the goal · 8'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'hard',
    shape: 'square',
    kind: 'normal',
    targets: 2,
    keyGroups: 0,
    target: 40,
    size: 19,
    depth: 9,
  },
  {
    id: 9,
    title: ['分开收尾', 'Trace the goal · 9'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'relief',
    shape: 'square',
    kind: 'normal',
    targets: 2,
    keyGroups: 0,
    target: 32,
    size: 19,
    depth: 6,
  },
  {
    id: 10,
    title: ['近路远挡', 'Trace the goal · 10'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'normal',
    shape: 'square',
    kind: 'normal',
    targets: 1,
    keyGroups: 0,
    target: 34,
    size: 19,
    depth: 8,
  },
  {
    id: 11,
    title: ['空隙不是出口', 'Trace the goal · 11'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'hard',
    shape: 'ring',
    kind: 'normal',
    targets: 1,
    keyGroups: 0,
    target: 38,
    size: 19,
    depth: 9,
  },
  {
    id: 12,
    title: ['换个方向读', 'Trace the goal · 12'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'normal',
    shape: 'square',
    kind: 'normal',
    targets: 1,
    keyGroups: 0,
    target: 33,
    size: 19,
    depth: 8,
  },
  {
    id: 13,
    title: ['先看第二层', 'Trace the goal · 13'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'hard',
    shape: 'square',
    kind: 'normal',
    targets: 1,
    keyGroups: 0,
    target: 37,
    size: 19,
    depth: 9,
  },
  {
    id: 14,
    title: ['中桥两岸', 'Trace the goal · 14'],
    focus: [
      '看清尖端方向，移走全部箭头。',
      'Follow each tip and free every arrow.',
    ],
    tier: 'normal',
    shape: 'islands',
    kind: 'normal',
    targets: 0,
    keyGroups: 0,
    target: 35,
    size: 19,
    depth: 0,
  },
  {
    id: 15,
    title: ['星旁留白', 'Trace the goal · 15'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'normal',
    shape: 'square',
    kind: 'normal',
    targets: 1,
    keyGroups: 0,
    target: 33,
    size: 19,
    depth: 10,
  },
  {
    id: 16,
    title: ['小箭大用', 'Trace the goal · 16'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'normal',
    shape: 'square',
    kind: 'normal',
    targets: 2,
    keyGroups: 0,
    target: 34,
    size: 19,
    depth: 7,
  },
  {
    id: 17,
    title: ['不必拆外圈', 'Trace the goal · 17'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'normal',
    shape: 'ring',
    kind: 'normal',
    targets: 1,
    keyGroups: 0,
    target: 35,
    size: 19,
    depth: 7,
  },
  {
    id: 18,
    title: ['两线相会', 'Trace the goal · 18'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'hard',
    shape: 'cross',
    kind: 'normal',
    targets: 2,
    keyGroups: 0,
    target: 36,
    size: 19,
    depth: 7,
  },
  {
    id: 19,
    title: ['一处宽松', 'Trace the goal · 19'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'relief',
    shape: 'islands',
    kind: 'normal',
    targets: 2,
    keyGroups: 0,
    target: 33,
    size: 19,
    depth: 9,
  },
  {
    id: 20,
    title: ['从里向外', 'Trace the goal · 20'],
    focus: [
      '看清尖端方向，移走全部箭头。',
      'Follow each tip and free every arrow.',
    ],
    tier: 'normal',
    shape: 'ring',
    kind: 'normal',
    targets: 0,
    keyGroups: 0,
    target: 35,
    size: 19,
    depth: 0,
  },
  {
    id: 21,
    title: ['双重检查', 'Trace the goal · 21'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'normal',
    shape: 'square',
    kind: 'normal',
    targets: 1,
    keyGroups: 0,
    target: 33,
    size: 19,
    depth: 11,
  },
  {
    id: 22,
    title: ['可走也可留', 'Trace the goal · 22'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'hard',
    shape: 'square',
    kind: 'normal',
    targets: 1,
    keyGroups: 0,
    target: 37,
    size: 19,
    depth: 10,
  },
  {
    id: 23,
    title: ['线身是阻挡', 'Trace the goal · 23'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'normal',
    shape: 'square',
    kind: 'mixed',
    targets: 1,
    keyGroups: 0,
    target: 35,
    size: 19,
    depth: 9,
  },
  {
    id: 24,
    title: ['分叉再汇合', 'Trace the goal · 24'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'hard',
    shape: 'square',
    kind: 'normal',
    targets: 2,
    keyGroups: 0,
    target: 36,
    size: 19,
    depth: 8,
  },
  {
    id: 25,
    title: ['顺手的两段', 'Trace the goal · 25'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'relief',
    shape: 'wings',
    kind: 'normal',
    targets: 2,
    keyGroups: 0,
    target: 33,
    size: 19,
    depth: 7,
  },
  {
    id: 26,
    title: ['不对称的星', 'Trace the goal · 26'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'normal',
    shape: 'ring',
    kind: 'normal',
    targets: 2,
    keyGroups: 0,
    target: 35,
    size: 19,
    depth: 6,
  },
  {
    id: 27,
    title: ['身边是假支', 'Trace the goal · 27'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'hard',
    shape: 'square',
    kind: 'normal',
    targets: 1,
    keyGroups: 0,
    target: 36,
    size: 19,
    depth: 10,
  },
  {
    id: 28,
    title: ['双出口一目标', 'Trace the goal · 28'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'normal',
    shape: 'square',
    kind: 'normal',
    targets: 1,
    keyGroups: 0,
    target: 34,
    size: 19,
    depth: 9,
  },
  {
    id: 29,
    title: ['三瓣归拢', 'Trace the goal · 29'],
    focus: [
      '看清尖端方向，移走全部箭头。',
      'Follow each tip and free every arrow.',
    ],
    tier: 'normal',
    shape: 'square',
    kind: 'normal',
    targets: 0,
    keyGroups: 0,
    target: 35,
    size: 19,
    depth: 0,
  },
  {
    id: 30,
    title: ['起步已会', 'Trace the goal · 30'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'hard',
    shape: 'diamond',
    kind: 'normal',
    targets: 2,
    keyGroups: 0,
    target: 38,
    size: 19,
    depth: 9,
  },
  {
    id: 31,
    title: ['两星三岔', 'Shared routes · 31'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'normal',
    shape: 'three-islands',
    kind: 'normal',
    targets: 2,
    keyGroups: 0,
    target: 40,
    size: 19,
    depth: 5,
  },
  {
    id: 32,
    title: ['各有后手', 'Shared routes · 32'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'normal',
    shape: 'wings',
    kind: 'normal',
    targets: 2,
    keyGroups: 0,
    target: 41,
    size: 19,
    depth: 10,
  },
  {
    id: 33,
    title: ['共用远端', 'Shared routes · 33'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'hard',
    shape: 'square',
    kind: 'normal',
    targets: 2,
    keyGroups: 0,
    target: 42,
    size: 19,
    depth: 6,
  },
  {
    id: 34,
    title: ['一星在路上', 'Shared routes · 34'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'normal',
    shape: 'square',
    kind: 'normal',
    targets: 2,
    keyGroups: 0,
    target: 40,
    size: 19,
    depth: 9,
  },
  {
    id: 35,
    title: ['双叉松开', 'Shared routes · 35'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'relief',
    shape: 'square',
    kind: 'normal',
    targets: 2,
    keyGroups: 0,
    target: 40,
    size: 19,
    depth: 9,
  },
  {
    id: 36,
    title: ['同列不同层', 'Shared routes · 36'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'hard',
    shape: 'square',
    kind: 'normal',
    targets: 2,
    keyGroups: 0,
    target: 42,
    size: 19,
    depth: 8,
  },
  {
    id: 37,
    title: ['可留的中间', 'Shared routes · 37'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'normal',
    shape: 'square',
    kind: 'normal',
    targets: 2,
    keyGroups: 0,
    target: 40,
    size: 19,
    depth: 10,
  },
  {
    id: 38,
    title: ['三支取两支', 'Shared routes · 38'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'hard',
    shape: 'square',
    kind: 'normal',
    targets: 2,
    keyGroups: 0,
    target: 44,
    size: 19,
    depth: 8,
  },
  {
    id: 39,
    title: ['共根异长', 'Shared routes · 39'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'normal',
    shape: 'square',
    kind: 'normal',
    targets: 2,
    keyGroups: 0,
    target: 39,
    size: 19,
    depth: 9,
  },
  {
    id: 40,
    title: ['先后皆可', 'Shared routes · 40'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'relief',
    shape: 'square',
    kind: 'normal',
    targets: 2,
    keyGroups: 0,
    target: 39,
    size: 19,
    depth: 8,
  },
  {
    id: 41,
    title: ['解开四区', 'Shared routes · 41'],
    focus: [
      '看清尖端方向，移走全部箭头。',
      'Follow each tip and free every arrow.',
    ],
    tier: 'normal',
    shape: 'square',
    kind: 'normal',
    targets: 0,
    keyGroups: 0,
    target: 41,
    size: 19,
    depth: 0,
  },
  {
    id: 42,
    title: ['一条短横梁', 'Shared routes · 42'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'hard',
    shape: 'square',
    kind: 'normal',
    targets: 2,
    keyGroups: 0,
    target: 42,
    size: 19,
    depth: 6,
  },
  {
    id: 43,
    title: ['双星背向', 'Shared routes · 43'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'normal',
    shape: 'ring',
    kind: 'normal',
    targets: 2,
    keyGroups: 0,
    target: 40,
    size: 19,
    depth: 10,
  },
  {
    id: 44,
    title: ['前后两个关口', 'Shared routes · 44'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'hard',
    shape: 'hourglass',
    kind: 'normal',
    targets: 2,
    keyGroups: 0,
    target: 44,
    size: 19,
    depth: 10,
  },
  {
    id: 45,
    title: ['只松一处', 'Shared routes · 45'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'relief',
    shape: 'square',
    kind: 'normal',
    targets: 2,
    keyGroups: 0,
    target: 38,
    size: 19,
    depth: 10,
  },
  {
    id: 46,
    title: ['四路筛选', 'Shared routes · 46'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'hard',
    shape: 'square',
    kind: 'normal',
    targets: 2,
    keyGroups: 0,
    target: 45,
    size: 19,
    depth: 9,
  },
  {
    id: 47,
    title: ['目标旁的出口', 'Shared routes · 47'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'normal',
    shape: 'square',
    kind: 'normal',
    targets: 2,
    keyGroups: 0,
    target: 41,
    size: 19,
    depth: 6,
  },
  {
    id: 48,
    title: ['错层的连接', 'Shared routes · 48'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'hard',
    shape: 'islands',
    kind: 'normal',
    targets: 2,
    keyGroups: 0,
    target: 42,
    size: 19,
    depth: 10,
  },
  {
    id: 49,
    title: ['留住外翼', 'Shared routes · 49'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'normal',
    shape: 'wings',
    kind: 'normal',
    targets: 2,
    keyGroups: 0,
    target: 40,
    size: 19,
    depth: 9,
  },
  {
    id: 50,
    title: ['半盘已通', 'Shared routes · 50'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'relief',
    shape: 'square',
    kind: 'normal',
    targets: 2,
    keyGroups: 0,
    target: 40,
    size: 19,
    depth: 8,
  },
  {
    id: 51,
    title: ['一个目标两把关', 'Shared routes · 51'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'hard',
    shape: 'square',
    kind: 'normal',
    targets: 2,
    keyGroups: 0,
    target: 42,
    size: 19,
    depth: 7,
  },
  {
    id: 52,
    title: ['长线短依赖', 'Shared routes · 52'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'normal',
    shape: 'islands',
    kind: 'mixed',
    targets: 2,
    keyGroups: 0,
    target: 40,
    size: 19,
    depth: 9,
  },
  {
    id: 53,
    title: ['中间不能略过', 'Shared routes · 53'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'hard',
    shape: 'ring',
    kind: 'normal',
    targets: 2,
    keyGroups: 0,
    target: 44,
    size: 19,
    depth: 9,
  },
  {
    id: 54,
    title: ['双星开花', 'Shared routes · 54'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'relief',
    shape: 'square',
    kind: 'normal',
    targets: 2,
    keyGroups: 0,
    target: 38,
    size: 19,
    depth: 10,
  },
  {
    id: 55,
    title: ['独立后再共享', 'Shared routes · 55'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'normal',
    shape: 'square',
    kind: 'normal',
    targets: 2,
    keyGroups: 0,
    target: 40,
    size: 19,
    depth: 9,
  },
  {
    id: 56,
    title: ['星挡星', 'Shared routes · 56'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'hard',
    shape: 'square',
    kind: 'normal',
    targets: 2,
    keyGroups: 0,
    target: 44,
    size: 19,
    depth: 9,
  },
  {
    id: 57,
    title: ['横向借道', 'Shared routes · 57'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'normal',
    shape: 'square',
    kind: 'normal',
    targets: 2,
    keyGroups: 0,
    target: 39,
    size: 19,
    depth: 7,
  },
  {
    id: 58,
    title: ['留下两角', 'Shared routes · 58'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'relief',
    shape: 'square',
    kind: 'normal',
    targets: 2,
    keyGroups: 0,
    target: 39,
    size: 19,
    depth: 9,
  },
  {
    id: 59,
    title: ['双关口回看', 'Shared routes · 59'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'hard',
    shape: 'ring',
    kind: 'normal',
    targets: 2,
    keyGroups: 0,
    target: 44,
    size: 19,
    depth: 10,
  },
  {
    id: 60,
    title: ['双星独立解', 'Shared routes · 60'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'hard',
    shape: 'six-windows',
    kind: 'normal',
    targets: 2,
    keyGroups: 0,
    target: 44,
    size: 19,
    depth: 9,
  },
  {
    id: 61,
    title: ['对岸挡路', 'Across the gap · 61'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'normal',
    shape: 'islands',
    kind: 'normal',
    targets: 2,
    keyGroups: 0,
    target: 46,
    size: 21,
    depth: 10,
  },
  {
    id: 62,
    title: ['连续两道空隙', 'Across the gap · 62'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'hard',
    shape: 'three-islands',
    kind: 'normal',
    targets: 2,
    keyGroups: 0,
    target: 50,
    size: 21,
    depth: 10,
  },
  {
    id: 63,
    title: ['环外才通', 'Across the gap · 63'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'normal',
    shape: 'ring',
    kind: 'normal',
    targets: 2,
    keyGroups: 0,
    target: 45,
    size: 21,
    depth: 8,
  },
  {
    id: 64,
    title: ['沿线找尖', 'Across the gap · 64'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'normal',
    shape: 'square',
    kind: 'mixed',
    targets: 2,
    keyGroups: 0,
    target: 46,
    size: 21,
    depth: 9,
  },
  {
    id: 65,
    title: ['远近相接', 'Across the gap · 65'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'relief',
    shape: 'square',
    kind: 'normal',
    targets: 2,
    keyGroups: 0,
    target: 46,
    size: 21,
    depth: 10,
  },
  {
    id: 66,
    title: ['空列也有下文', 'Across the gap · 66'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'hard',
    shape: 'islands',
    kind: 'normal',
    targets: 2,
    keyGroups: 0,
    target: 48,
    size: 21,
    depth: 9,
  },
  {
    id: 67,
    title: ['隔岸共梁', 'Across the gap · 67'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'hard',
    shape: 'four-islands',
    kind: 'normal',
    targets: 2,
    keyGroups: 0,
    target: 51,
    size: 21,
    depth: 8,
  },
  {
    id: 68,
    title: ['两种空窗', 'Across the gap · 68'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'normal',
    shape: 'islands',
    kind: 'normal',
    targets: 2,
    keyGroups: 0,
    target: 47,
    size: 21,
    depth: 7,
  },
  {
    id: 69,
    title: ['长尾不相关', 'Across the gap · 69'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'normal',
    shape: 'square',
    kind: 'mixed',
    targets: 2,
    keyGroups: 0,
    target: 45,
    size: 21,
    depth: 9,
  },
  {
    id: 70,
    title: ['两岸松动', 'Across the gap · 70'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'relief',
    shape: 'islands',
    kind: 'normal',
    targets: 2,
    keyGroups: 0,
    target: 45,
    size: 21,
    depth: 7,
  },
  {
    id: 71,
    title: ['外圈回到内圈', 'Across the gap · 71'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'hard',
    shape: 'ring',
    kind: 'normal',
    targets: 2,
    keyGroups: 0,
    target: 50,
    size: 21,
    depth: 7,
  },
  {
    id: 72,
    title: ['缺口偏一格', 'Across the gap · 72'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'normal',
    shape: 'square',
    kind: 'normal',
    targets: 2,
    keyGroups: 0,
    target: 45,
    size: 21,
    depth: 8,
  },
  {
    id: 73,
    title: ['三岸共根', 'Across the gap · 73'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'normal',
    shape: 'three-islands',
    kind: 'normal',
    targets: 3,
    keyGroups: 0,
    target: 46,
    size: 21,
    depth: 10,
  },
  {
    id: 74,
    title: ['星在长线末', 'Across the gap · 74'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'hard',
    shape: 'square',
    kind: 'mixed',
    targets: 2,
    keyGroups: 0,
    target: 50,
    size: 21,
    depth: 9,
  },
  {
    id: 75,
    title: ['空心也相连', 'Across the gap · 75'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'relief',
    shape: 'ring',
    kind: 'normal',
    targets: 3,
    keyGroups: 0,
    target: 44,
    size: 21,
    depth: 7,
  },
  {
    id: 76,
    title: ['两岸两关口', 'Across the gap · 76'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'hard',
    shape: 'islands',
    kind: 'normal',
    targets: 2,
    keyGroups: 0,
    target: 49,
    size: 21,
    depth: 8,
  },
  {
    id: 77,
    title: ['空隙后的分叉', 'Across the gap · 77'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'normal',
    shape: 'islands',
    kind: 'normal',
    targets: 2,
    keyGroups: 0,
    target: 47,
    size: 21,
    depth: 8,
  },
  {
    id: 78,
    title: ['中央长梁', 'Across the gap · 78'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'hard',
    shape: 'square',
    kind: 'mixed',
    targets: 3,
    keyGroups: 0,
    target: 48,
    size: 21,
    depth: 10,
  },
  {
    id: 79,
    title: ['短线跨全盘', 'Across the gap · 79'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'normal',
    shape: 'square',
    kind: 'mixed',
    targets: 2,
    keyGroups: 0,
    target: 46,
    size: 21,
    depth: 10,
  },
  {
    id: 80,
    title: ['三岸顺行', 'Across the gap · 80'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'relief',
    shape: 'three-islands',
    kind: 'normal',
    targets: 3,
    keyGroups: 0,
    target: 46,
    size: 21,
    depth: 9,
  },
  {
    id: 81,
    title: ['留白交会', 'Across the gap · 81'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'hard',
    shape: 'cross',
    kind: 'normal',
    targets: 2,
    keyGroups: 0,
    target: 48,
    size: 21,
    depth: 9,
  },
  {
    id: 82,
    title: ['同岸不同线', 'Across the gap · 82'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'normal',
    shape: 'islands',
    kind: 'normal',
    targets: 2,
    keyGroups: 0,
    target: 46,
    size: 21,
    depth: 7,
  },
  {
    id: 83,
    title: ['外翼的根', 'Across the gap · 83'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'hard',
    shape: 'wings',
    kind: 'normal',
    targets: 3,
    keyGroups: 0,
    target: 50,
    size: 21,
    depth: 10,
  },
  {
    id: 84,
    title: ['回钩后的通道', 'Across the gap · 84'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'normal',
    shape: 'square',
    kind: 'mixed',
    targets: 2,
    keyGroups: 0,
    target: 45,
    size: 21,
    depth: 8,
  },
  {
    id: 85,
    title: ['远端仍要看', 'Across the gap · 85'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'relief',
    shape: 'islands',
    kind: 'normal',
    targets: 3,
    keyGroups: 0,
    target: 45,
    size: 21,
    depth: 10,
  },
  {
    id: 86,
    title: ['两个共享中心', 'Across the gap · 86'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'hard',
    shape: 'three-islands',
    kind: 'normal',
    targets: 3,
    keyGroups: 0,
    target: 50,
    size: 21,
    depth: 8,
  },
  {
    id: 87,
    title: ['星先过桥', 'Across the gap · 87'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'normal',
    shape: 'ring',
    kind: 'normal',
    targets: 2,
    keyGroups: 0,
    target: 45,
    size: 21,
    depth: 9,
  },
  {
    id: 88,
    title: ['一岸可以留', 'Across the gap · 88'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'normal',
    shape: 'four-islands',
    kind: 'normal',
    targets: 3,
    keyGroups: 0,
    target: 46,
    size: 21,
    depth: 11,
  },
  {
    id: 89,
    title: ['连续回溯', 'Across the gap · 89'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'hard',
    shape: 'ring',
    kind: 'normal',
    targets: 3,
    keyGroups: 0,
    target: 52,
    size: 21,
    depth: 9,
  },
  {
    id: 90,
    title: ['看懂全盘', 'Across the gap · 90'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'normal',
    shape: 'six-windows',
    kind: 'normal',
    targets: 3,
    keyGroups: 0,
    target: 45,
    size: 21,
    depth: 8,
  },
  {
    id: 91,
    title: ['开锁之后', 'Keys and exits · 91'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'normal',
    shape: 'square',
    kind: 'normal',
    targets: 2,
    keyGroups: 1,
    target: 50,
    size: 21,
    depth: 9,
  },
  {
    id: 92,
    title: ['钥匙在对岸', 'Keys and exits · 92'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'normal',
    shape: 'islands',
    kind: 'normal',
    targets: 2,
    keyGroups: 1,
    target: 51,
    size: 21,
    depth: 8,
  },
  {
    id: 93,
    title: ['锁住的横梁', 'Keys and exits · 93'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'hard',
    shape: 'cross',
    kind: 'normal',
    targets: 2,
    keyGroups: 1,
    target: 52,
    size: 21,
    depth: 9,
  },
  {
    id: 94,
    title: ['同字不同路', 'Keys and exits · 94'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'normal',
    shape: 'square',
    kind: 'normal',
    targets: 2,
    keyGroups: 1,
    target: 50,
    size: 21,
    depth: 9,
  },
  {
    id: 95,
    title: ['一锁两翼', 'Keys and exits · 95'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'relief',
    shape: 'wings',
    kind: 'normal',
    targets: 2,
    keyGroups: 1,
    target: 50,
    size: 21,
    depth: 10,
  },
  {
    id: 96,
    title: ['星也是钥匙', 'Keys and exits · 96'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'hard',
    shape: 'three-islands',
    kind: 'normal',
    targets: 2,
    keyGroups: 1,
    target: 54,
    size: 21,
    depth: 9,
  },
  {
    id: 97,
    title: ['钥匙不在锁旁', 'Keys and exits · 97'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'normal',
    shape: 'square',
    kind: 'normal',
    targets: 2,
    keyGroups: 1,
    target: 50,
    size: 21,
    depth: 10,
  },
  {
    id: 98,
    title: ['一个锁两条件', 'Keys and exits · 98'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'hard',
    shape: 'ring',
    kind: 'normal',
    targets: 2,
    keyGroups: 1,
    target: 54,
    size: 21,
    depth: 8,
  },
  {
    id: 99,
    title: ['自由支路有用', 'Keys and exits · 99'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'normal',
    shape: 'square',
    kind: 'normal',
    targets: 2,
    keyGroups: 1,
    target: 49,
    size: 21,
    depth: 10,
  },
  {
    id: 100,
    title: ['开门见两星', 'Keys and exits · 100'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'normal',
    shape: 'square',
    kind: 'normal',
    targets: 2,
    keyGroups: 1,
    target: 50,
    size: 21,
    depth: 10,
  },
  {
    id: 101,
    title: ['无锁星先走', 'Keys and exits · 101'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'normal',
    shape: 'islands',
    kind: 'normal',
    targets: 2,
    keyGroups: 1,
    target: 51,
    size: 21,
    depth: 12,
  },
  {
    id: 102,
    title: ['长身带锁', 'Keys and exits · 102'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'hard',
    shape: 'square',
    kind: 'mixed',
    targets: 2,
    keyGroups: 1,
    target: 52,
    size: 21,
    depth: 9,
  },
  {
    id: 103,
    title: ['两扇门一把钥匙', 'Keys and exits · 103'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'relief',
    shape: 'square',
    kind: 'normal',
    targets: 3,
    keyGroups: 1,
    target: 49,
    size: 21,
    depth: 12,
  },
  {
    id: 104,
    title: ['有门也可留', 'Keys and exits · 104'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'hard',
    shape: 'ring',
    kind: 'normal',
    targets: 2,
    keyGroups: 1,
    target: 54,
    size: 21,
    depth: 13,
  },
  {
    id: 105,
    title: ['共同钥路', 'Keys and exits · 105'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'normal',
    shape: 'square',
    kind: 'normal',
    targets: 3,
    keyGroups: 1,
    target: 49,
    size: 21,
    depth: 10,
  },
  {
    id: 106,
    title: ['解锁还差一岸', 'Keys and exits · 106'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'normal',
    shape: 'four-islands',
    kind: 'normal',
    targets: 2,
    keyGroups: 1,
    target: 50,
    size: 21,
    depth: 6,
  },
  {
    id: 107,
    title: ['钥匙前的共根', 'Keys and exits · 107'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'hard',
    shape: 'square',
    kind: 'normal',
    targets: 2,
    keyGroups: 1,
    target: 54,
    size: 21,
    depth: 9,
  },
  {
    id: 108,
    title: ['锁在第二层', 'Keys and exits · 108'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'normal',
    shape: 'square',
    kind: 'normal',
    targets: 2,
    keyGroups: 1,
    target: 49,
    size: 21,
    depth: 12,
  },
  {
    id: 109,
    title: ['两条路先准备', 'Keys and exits · 109'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'hard',
    shape: 'three-islands',
    kind: 'normal',
    targets: 3,
    keyGroups: 1,
    target: 53,
    size: 21,
    depth: 10,
  },
  {
    id: 110,
    title: ['开锁顺势解', 'Keys and exits · 110'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'relief',
    shape: 'square',
    kind: 'normal',
    targets: 3,
    keyGroups: 1,
    target: 50,
    size: 21,
    depth: 6,
  },
  {
    id: 111,
    title: ['钥匙尾巴挡路', 'Keys and exits · 111'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'normal',
    shape: 'square',
    kind: 'normal',
    targets: 2,
    keyGroups: 1,
    target: 49,
    size: 21,
    depth: 10,
  },
  {
    id: 112,
    title: ['锁外的外圈', 'Keys and exits · 112'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'hard',
    shape: 'ring',
    kind: 'normal',
    targets: 2,
    keyGroups: 1,
    target: 53,
    size: 21,
    depth: 11,
  },
  {
    id: 113,
    title: ['双锁单阻挡', 'Keys and exits · 113'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'normal',
    shape: 'square',
    kind: 'normal',
    targets: 3,
    keyGroups: 1,
    target: 51,
    size: 21,
    depth: 10,
  },
  {
    id: 114,
    title: ['锁前换区', 'Keys and exits · 114'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'hard',
    shape: 'islands',
    kind: 'normal',
    targets: 2,
    keyGroups: 1,
    target: 52,
    size: 21,
    depth: 10,
  },
  {
    id: 115,
    title: ['字母相同仍核对', 'Keys and exits · 115'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'normal',
    shape: 'square',
    kind: 'normal',
    targets: 3,
    keyGroups: 1,
    target: 50,
    size: 21,
    depth: 11,
  },
  {
    id: 116,
    title: ['钥匙与星共根', 'Keys and exits · 116'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'normal',
    shape: 'square',
    kind: 'normal',
    targets: 2,
    keyGroups: 1,
    target: 51,
    size: 21,
    depth: 12,
  },
  {
    id: 117,
    title: ['空路有锁', 'Keys and exits · 117'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'hard',
    shape: 'cross',
    kind: 'normal',
    targets: 2,
    keyGroups: 1,
    target: 52,
    size: 21,
    depth: 9,
  },
  {
    id: 118,
    title: ['开锁释放桥', 'Keys and exits · 118'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'relief',
    shape: 'four-islands',
    kind: 'normal',
    targets: 3,
    keyGroups: 1,
    target: 49,
    size: 21,
    depth: 10,
  },
  {
    id: 119,
    title: ['权限与路线', 'Keys and exits · 119'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'hard',
    shape: 'six-windows',
    kind: 'normal',
    targets: 3,
    keyGroups: 1,
    target: 56,
    size: 21,
    depth: 7,
  },
  {
    id: 120,
    title: ['一把钥匙的全局', 'Keys and exits · 120'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'normal',
    shape: 'ring',
    kind: 'normal',
    targets: 3,
    keyGroups: 1,
    target: 49,
    size: 21,
    depth: 8,
  },
  {
    id: 121,
    title: ['两个字母', 'Two-key connections · 121'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'normal',
    shape: 'square',
    kind: 'normal',
    targets: 2,
    keyGroups: 2,
    target: 54,
    size: 23,
    depth: 10,
  },
  {
    id: 122,
    title: ['A先开B', 'Two-key connections · 122'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'normal',
    shape: 'square',
    kind: 'normal',
    targets: 2,
    keyGroups: 2,
    target: 55,
    size: 23,
    depth: 8,
  },
  {
    id: 123,
    title: ['字母交错', 'Two-key connections · 123'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'hard',
    shape: 'islands',
    kind: 'normal',
    targets: 2,
    keyGroups: 2,
    target: 56,
    size: 23,
    depth: 11,
  },
  {
    id: 124,
    title: ['钥匙都在外', 'Two-key connections · 124'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'normal',
    shape: 'ring',
    kind: 'normal',
    targets: 3,
    keyGroups: 2,
    target: 54,
    size: 23,
    depth: 11,
  },
  {
    id: 125,
    title: ['双门顺行', 'Two-key connections · 125'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'relief',
    shape: 'square',
    kind: 'normal',
    targets: 3,
    keyGroups: 2,
    target: 54,
    size: 23,
    depth: 10,
  },
  {
    id: 126,
    title: ['B先开A', 'Two-key connections · 126'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'hard',
    shape: 'square',
    kind: 'normal',
    targets: 2,
    keyGroups: 2,
    target: 56,
    size: 23,
    depth: 9,
  },
  {
    id: 127,
    title: ['一星持A', 'Two-key connections · 127'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'normal',
    shape: 'three-islands',
    kind: 'normal',
    targets: 3,
    keyGroups: 2,
    target: 54,
    size: 23,
    depth: 11,
  },
  {
    id: 128,
    title: ['一道门两层', 'Two-key connections · 128'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'hard',
    shape: 'square',
    kind: 'normal',
    targets: 2,
    keyGroups: 2,
    target: 58,
    size: 23,
    depth: 13,
  },
  {
    id: 129,
    title: ['无锁的共根', 'Two-key connections · 129'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'normal',
    shape: 'square',
    kind: 'normal',
    targets: 3,
    keyGroups: 2,
    target: 53,
    size: 23,
    depth: 10,
  },
  {
    id: 130,
    title: ['双钥短收尾', 'Two-key connections · 130'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'normal',
    shape: 'square',
    kind: 'normal',
    targets: 3,
    keyGroups: 2,
    target: 54,
    size: 23,
    depth: 11,
  },
  {
    id: 131,
    title: ['开A不等于开B', 'Two-key connections · 131'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'hard',
    shape: 'square',
    kind: 'normal',
    targets: 2,
    keyGroups: 2,
    target: 58,
    size: 23,
    depth: 12,
  },
  {
    id: 132,
    title: ['钥匙线身相接', 'Two-key connections · 132'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'relief',
    shape: 'square',
    kind: 'normal',
    targets: 3,
    keyGroups: 2,
    target: 52,
    size: 23,
    depth: 12,
  },
  {
    id: 133,
    title: ['两星接力', 'Two-key connections · 133'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'hard',
    shape: 'three-islands',
    kind: 'normal',
    targets: 3,
    keyGroups: 2,
    target: 59,
    size: 23,
    depth: 12,
  },
  {
    id: 134,
    title: ['门外另有横梁', 'Two-key connections · 134'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'hard',
    shape: 'square',
    kind: 'normal',
    targets: 3,
    keyGroups: 2,
    target: 58,
    size: 23,
    depth: 13,
  },
  {
    id: 135,
    title: ['两字母各归位', 'Two-key connections · 135'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'normal',
    shape: 'square',
    kind: 'normal',
    targets: 3,
    keyGroups: 2,
    target: 53,
    size: 23,
    depth: 11,
  },
  {
    id: 136,
    title: ['第三片可留', 'Two-key connections · 136'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'normal',
    shape: 'three-islands',
    kind: 'normal',
    targets: 2,
    keyGroups: 2,
    target: 54,
    size: 23,
    depth: 10,
  },
  {
    id: 137,
    title: ['无锁星开局', 'Two-key connections · 137'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'hard',
    shape: 'square',
    kind: 'normal',
    targets: 3,
    keyGroups: 2,
    target: 58,
    size: 23,
    depth: 13,
  },
  {
    id: 138,
    title: ['交叠的两条链', 'Two-key connections · 138'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'normal',
    shape: 'square',
    kind: 'normal',
    targets: 3,
    keyGroups: 2,
    target: 53,
    size: 23,
    depth: 12,
  },
  {
    id: 139,
    title: ['开锁看对岸', 'Two-key connections · 139'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'hard',
    shape: 'ring',
    kind: 'normal',
    targets: 2,
    keyGroups: 2,
    target: 57,
    size: 23,
    depth: 12,
  },
  {
    id: 140,
    title: ['先解共同段', 'Two-key connections · 140'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'relief',
    shape: 'square',
    kind: 'normal',
    targets: 3,
    keyGroups: 2,
    target: 54,
    size: 23,
    depth: 9,
  },
  {
    id: 141,
    title: ['锁住关键支点', 'Two-key connections · 141'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'normal',
    shape: 'square',
    kind: 'normal',
    targets: 3,
    keyGroups: 2,
    target: 53,
    size: 23,
    depth: 10,
  },
  {
    id: 142,
    title: ['一钥两用途', 'Two-key connections · 142'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'hard',
    shape: 'square',
    kind: 'normal',
    targets: 2,
    keyGroups: 2,
    target: 57,
    size: 23,
    depth: 13,
  },
  {
    id: 143,
    title: ['钥匙都能先取', 'Two-key connections · 143'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'normal',
    shape: 'square',
    kind: 'normal',
    targets: 3,
    keyGroups: 2,
    target: 55,
    size: 23,
    depth: 9,
  },
  {
    id: 144,
    title: ['两道锁不相邻', 'Two-key connections · 144'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'hard',
    shape: 'four-islands',
    kind: 'normal',
    targets: 3,
    keyGroups: 2,
    target: 56,
    size: 23,
    depth: 10,
  },
  {
    id: 145,
    title: ['双锁仍有余地', 'Two-key connections · 145'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'normal',
    shape: 'islands',
    kind: 'normal',
    targets: 3,
    keyGroups: 2,
    target: 54,
    size: 23,
    depth: 10,
  },
  {
    id: 146,
    title: ['普通星连两钥', 'Two-key connections · 146'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'normal',
    shape: 'ring',
    kind: 'normal',
    targets: 3,
    keyGroups: 2,
    target: 55,
    size: 23,
    depth: 10,
  },
  {
    id: 147,
    title: ['门里有外路', 'Two-key connections · 147'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'hard',
    shape: 'square',
    kind: 'normal',
    targets: 2,
    keyGroups: 2,
    target: 56,
    size: 23,
    depth: 11,
  },
  {
    id: 148,
    title: ['字母与方向分开', 'Two-key connections · 148'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'relief',
    shape: 'square',
    kind: 'normal',
    targets: 3,
    keyGroups: 2,
    target: 53,
    size: 23,
    depth: 10,
  },
  {
    id: 149,
    title: ['逆向钥路', 'Two-key connections · 149'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'hard',
    shape: 'three-islands',
    kind: 'normal',
    targets: 3,
    keyGroups: 2,
    target: 60,
    size: 23,
    depth: 11,
  },
  {
    id: 150,
    title: ['双钥已掌握', 'Two-key connections · 150'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'normal',
    shape: 'six-windows',
    kind: 'normal',
    targets: 3,
    keyGroups: 2,
    target: 53,
    size: 23,
    depth: 9,
  },
  {
    id: 151,
    title: ['两对共同段', 'Three-star overlaps · 151'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'normal',
    shape: 'square',
    kind: 'normal',
    targets: 3,
    keyGroups: 2,
    target: 58,
    size: 23,
    depth: 10,
  },
  {
    id: 152,
    title: ['三星一个根', 'Three-star overlaps · 152'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'normal',
    shape: 'square',
    kind: 'normal',
    targets: 3,
    keyGroups: 2,
    target: 59,
    size: 23,
    depth: 12,
  },
  {
    id: 153,
    title: ['共用但不同层', 'Three-star overlaps · 153'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'hard',
    shape: 'square',
    kind: 'normal',
    targets: 3,
    keyGroups: 2,
    target: 60,
    size: 23,
    depth: 10,
  },
  {
    id: 154,
    title: ['先星再双门', 'Three-star overlaps · 154'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'normal',
    shape: 'three-islands',
    kind: 'normal',
    targets: 3,
    keyGroups: 2,
    target: 58,
    size: 23,
    depth: 11,
  },
  {
    id: 155,
    title: ['三路归一', 'Three-star overlaps · 155'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'relief',
    shape: 'square',
    kind: 'normal',
    targets: 3,
    keyGroups: 2,
    target: 58,
    size: 23,
    depth: 9,
  },
  {
    id: 156,
    title: ['三对交叠', 'Three-star overlaps · 156'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'hard',
    shape: 'square',
    kind: 'normal',
    targets: 3,
    keyGroups: 2,
    target: 60,
    size: 23,
    depth: 10,
  },
  {
    id: 157,
    title: ['孤立的第三星', 'Three-star overlaps · 157'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'normal',
    shape: 'wings',
    kind: 'normal',
    targets: 3,
    keyGroups: 2,
    target: 58,
    size: 23,
    depth: 10,
  },
  {
    id: 158,
    title: ['共根藏在钥前', 'Three-star overlaps · 158'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'hard',
    shape: 'four-islands',
    kind: 'normal',
    targets: 3,
    keyGroups: 2,
    target: 64,
    size: 23,
    depth: 13,
  },
  {
    id: 159,
    title: ['一星挡两星', 'Three-star overlaps · 159'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'normal',
    shape: 'square',
    kind: 'normal',
    targets: 3,
    keyGroups: 2,
    target: 57,
    size: 23,
    depth: 11,
  },
  {
    id: 160,
    title: ['三星舒展', 'Three-star overlaps · 160'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'normal',
    shape: 'square',
    kind: 'normal',
    targets: 3,
    keyGroups: 2,
    target: 58,
    size: 23,
    depth: 7,
  },
  {
    id: 161,
    title: ['全共享与半共享', 'Three-star overlaps · 161'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'hard',
    shape: 'ring',
    kind: 'normal',
    targets: 3,
    keyGroups: 2,
    target: 62,
    size: 23,
    depth: 12,
  },
  {
    id: 162,
    title: ['私有链穿中间', 'Three-star overlaps · 162'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'relief',
    shape: 'six-windows',
    kind: 'mixed',
    targets: 3,
    keyGroups: 2,
    target: 56,
    size: 23,
    depth: 11,
  },
  {
    id: 163,
    title: ['两星先后相接', 'Three-star overlaps · 163'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'hard',
    shape: 'three-islands',
    kind: 'normal',
    targets: 3,
    keyGroups: 2,
    target: 61,
    size: 23,
    depth: 12,
  },
  {
    id: 164,
    title: ['无关区含钥锁', 'Three-star overlaps · 164'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'normal',
    shape: 'square',
    kind: 'normal',
    targets: 3,
    keyGroups: 2,
    target: 59,
    size: 23,
    depth: 11,
  },
  {
    id: 165,
    title: ['先开共同窗', 'Three-star overlaps · 165'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'normal',
    shape: 'square',
    kind: 'normal',
    targets: 3,
    keyGroups: 2,
    target: 57,
    size: 23,
    depth: 11,
  },
  {
    id: 166,
    title: ['两层交集', 'Three-star overlaps · 166'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'hard',
    shape: 'square',
    kind: 'normal',
    targets: 3,
    keyGroups: 2,
    target: 61,
    size: 23,
    depth: 11,
  },
  {
    id: 167,
    title: ['三条不同出口', 'Three-star overlaps · 167'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'normal',
    shape: 'square',
    kind: 'mixed',
    targets: 3,
    keyGroups: 2,
    target: 59,
    size: 23,
    depth: 9,
  },
  {
    id: 168,
    title: ['一处同时解两锁路', 'Three-star overlaps · 168'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'hard',
    shape: 'cross',
    kind: 'normal',
    targets: 3,
    keyGroups: 2,
    target: 60,
    size: 23,
    depth: 13,
  },
  {
    id: 169,
    title: ['同一星两边看', 'Three-star overlaps · 169'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'normal',
    shape: 'wings',
    kind: 'normal',
    targets: 3,
    keyGroups: 2,
    target: 58,
    size: 23,
    depth: 10,
  },
  {
    id: 170,
    title: ['交叠但不拥挤', 'Three-star overlaps · 170'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'relief',
    shape: 'three-islands',
    kind: 'normal',
    targets: 3,
    keyGroups: 2,
    target: 58,
    size: 23,
    depth: 8,
  },
  {
    id: 171,
    title: ['一条可留长链', 'Three-star overlaps · 171'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'hard',
    shape: 'square',
    kind: 'mixed',
    targets: 3,
    keyGroups: 2,
    target: 60,
    size: 23,
    depth: 7,
  },
  {
    id: 172,
    title: ['先解外层共根', 'Three-star overlaps · 172'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'normal',
    shape: 'ring',
    kind: 'normal',
    targets: 3,
    keyGroups: 2,
    target: 58,
    size: 23,
    depth: 10,
  },
  {
    id: 173,
    title: ['共根不在最先', 'Three-star overlaps · 173'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'hard',
    shape: 'square',
    kind: 'normal',
    targets: 3,
    keyGroups: 2,
    target: 62,
    size: 23,
    depth: 8,
  },
  {
    id: 174,
    title: ['两个目标携钥匙', 'Three-star overlaps · 174'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'normal',
    shape: 'square',
    kind: 'normal',
    targets: 3,
    keyGroups: 2,
    target: 57,
    size: 23,
    depth: 14,
  },
  {
    id: 175,
    title: ['分清再顺行', 'Three-star overlaps · 175'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'normal',
    shape: 'square',
    kind: 'normal',
    targets: 3,
    keyGroups: 2,
    target: 58,
    size: 23,
    depth: 11,
  },
  {
    id: 176,
    title: ['目标间的普通桥', 'Three-star overlaps · 176'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'hard',
    shape: 'three-islands',
    kind: 'normal',
    targets: 3,
    keyGroups: 2,
    target: 62,
    size: 23,
    depth: 10,
  },
  {
    id: 177,
    title: ['三星不同权限', 'Three-star overlaps · 177'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'relief',
    shape: 'ring',
    kind: 'normal',
    targets: 3,
    keyGroups: 2,
    target: 56,
    size: 23,
    depth: 9,
  },
  {
    id: 178,
    title: ['一处完成两种工作', 'Three-star overlaps · 178'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'hard',
    shape: 'ring',
    kind: 'normal',
    targets: 3,
    keyGroups: 2,
    target: 61,
    size: 23,
    depth: 14,
  },
  {
    id: 179,
    title: ['三星集合题', 'Three-star overlaps · 179'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'hard',
    shape: 'six-windows',
    kind: 'normal',
    targets: 3,
    keyGroups: 2,
    target: 64,
    size: 23,
    depth: 8,
  },
  {
    id: 180,
    title: ['三路都看懂', 'Three-star overlaps · 180'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'normal',
    shape: 'square',
    kind: 'normal',
    targets: 3,
    keyGroups: 2,
    target: 57,
    size: 23,
    depth: 10,
  },
  {
    id: 181,
    title: ['看起来相交', 'Woven regions · 181'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'normal',
    shape: 'square',
    kind: 'normal',
    targets: 3,
    keyGroups: 2,
    target: 62,
    size: 25,
    depth: 13,
  },
  {
    id: 182,
    title: ['相邻不同任务', 'Woven regions · 182'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'hard',
    shape: 'square',
    kind: 'normal',
    targets: 3,
    keyGroups: 2,
    target: 66,
    size: 25,
    depth: 13,
  },
  {
    id: 183,
    title: ['长短相互挡', 'Woven regions · 183'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'normal',
    shape: 'square',
    kind: 'mixed',
    targets: 3,
    keyGroups: 2,
    target: 61,
    size: 25,
    depth: 11,
  },
  {
    id: 184,
    title: ['双层错位锁', 'Woven regions · 184'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'hard',
    shape: 'square',
    kind: 'normal',
    targets: 3,
    keyGroups: 2,
    target: 65,
    size: 25,
    depth: 11,
  },
  {
    id: 185,
    title: ['环芯不是共根', 'Woven regions · 185'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'normal',
    shape: 'ring',
    kind: 'normal',
    targets: 3,
    keyGroups: 2,
    target: 63,
    size: 25,
    depth: 9,
  },
  {
    id: 186,
    title: ['三个局部入口', 'Woven regions · 186'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'hard',
    shape: 'six-windows',
    kind: 'normal',
    targets: 3,
    keyGroups: 2,
    target: 64,
    size: 25,
    depth: 10,
  },
  {
    id: 187,
    title: ['分区看同一根', 'Woven regions · 187'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'relief',
    shape: 'islands',
    kind: 'normal',
    targets: 3,
    keyGroups: 2,
    target: 61,
    size: 25,
    depth: 11,
  },
  {
    id: 188,
    title: ['锁在长线中段', 'Woven regions · 188'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'normal',
    shape: 'square',
    kind: 'mixed',
    targets: 3,
    keyGroups: 2,
    target: 63,
    size: 25,
    depth: 16,
  },
  {
    id: 189,
    title: ['相似枝不同终点', 'Woven regions · 189'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'hard',
    shape: 'square',
    kind: 'normal',
    targets: 3,
    keyGroups: 2,
    target: 64,
    size: 25,
    depth: 11,
  },
  {
    id: 190,
    title: ['目标之间穿行', 'Woven regions · 190'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'normal',
    shape: 'square',
    kind: 'normal',
    targets: 3,
    keyGroups: 2,
    target: 62,
    size: 25,
    depth: 11,
  },
  {
    id: 191,
    title: ['反向的外圈', 'Woven regions · 191'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'hard',
    shape: 'ring',
    kind: 'normal',
    targets: 3,
    keyGroups: 2,
    target: 66,
    size: 25,
    depth: 14,
  },
  {
    id: 192,
    title: ['一段线两种阻挡', 'Woven regions · 192'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'normal',
    shape: 'square',
    kind: 'normal',
    targets: 3,
    keyGroups: 2,
    target: 61,
    size: 25,
    depth: 9,
  },
  {
    id: 193,
    title: ['拆开交织', 'Woven regions · 193'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'hard',
    shape: 'six-windows',
    kind: 'mixed',
    targets: 3,
    keyGroups: 2,
    target: 67,
    size: 25,
    depth: 10,
  },
  {
    id: 194,
    title: ['同结构更清楚', 'Woven regions · 194'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'relief',
    shape: 'six-windows',
    kind: 'normal',
    targets: 3,
    keyGroups: 2,
    target: 62,
    size: 25,
    depth: 8,
  },
  {
    id: 195,
    title: ['尖端在另一侧', 'Woven regions · 195'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'normal',
    shape: 'wings',
    kind: 'mixed',
    targets: 3,
    keyGroups: 2,
    target: 61,
    size: 25,
    depth: 11,
  },
  {
    id: 196,
    title: ['内层的可走箭头', 'Woven regions · 196'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'hard',
    shape: 'square',
    kind: 'normal',
    targets: 3,
    keyGroups: 2,
    target: 65,
    size: 25,
    depth: 14,
  },
  {
    id: 197,
    title: ['同字锁分三层', 'Woven regions · 197'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'normal',
    shape: 'square',
    kind: 'normal',
    targets: 3,
    keyGroups: 2,
    target: 63,
    size: 25,
    depth: 11,
  },
  {
    id: 198,
    title: ['长线绕过目标', 'Woven regions · 198'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'hard',
    shape: 'square',
    kind: 'mixed',
    targets: 3,
    keyGroups: 2,
    target: 64,
    size: 25,
    depth: 10,
  },
  {
    id: 199,
    title: ['共根在下方', 'Woven regions · 199'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'normal',
    shape: 'square',
    kind: 'normal',
    targets: 3,
    keyGroups: 2,
    target: 62,
    size: 25,
    depth: 8,
  },
  {
    id: 200,
    title: ['双门错着开', 'Woven regions · 200'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'hard',
    shape: 'square',
    kind: 'normal',
    targets: 3,
    keyGroups: 2,
    target: 66,
    size: 25,
    depth: 11,
  },
  {
    id: 201,
    title: ['留下内圈一半', 'Woven regions · 201'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'normal',
    shape: 'ring',
    kind: 'normal',
    targets: 3,
    keyGroups: 2,
    target: 61,
    size: 25,
    depth: 13,
  },
  {
    id: 202,
    title: ['给关系留空隙', 'Woven regions · 202'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'relief',
    shape: 'three-islands',
    kind: 'normal',
    targets: 3,
    keyGroups: 2,
    target: 61,
    size: 25,
    depth: 11,
  },
  {
    id: 203,
    title: ['两根梁三片区', 'Woven regions · 203'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'hard',
    shape: 'square',
    kind: 'normal',
    targets: 3,
    keyGroups: 2,
    target: 66,
    size: 25,
    depth: 10,
  },
  {
    id: 204,
    title: ['锁开后的错列', 'Woven regions · 204'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'normal',
    shape: 'square',
    kind: 'normal',
    targets: 3,
    keyGroups: 2,
    target: 61,
    size: 25,
    depth: 13,
  },
  {
    id: 205,
    title: ['星体也是桥', 'Woven regions · 205'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'hard',
    shape: 'three-islands',
    kind: 'mixed',
    targets: 3,
    keyGroups: 2,
    target: 65,
    size: 25,
    depth: 9,
  },
  {
    id: 206,
    title: ['路过但不需要', 'Woven regions · 206'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'normal',
    shape: 'square',
    kind: 'mixed',
    targets: 3,
    keyGroups: 2,
    target: 63,
    size: 25,
    depth: 11,
  },
  {
    id: 207,
    title: ['中间有空列', 'Woven regions · 207'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'hard',
    shape: 'square',
    kind: 'normal',
    targets: 3,
    keyGroups: 2,
    target: 64,
    size: 25,
    depth: 9,
  },
  {
    id: 208,
    title: ['交织后的舒展', 'Woven regions · 208'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'relief',
    shape: 'square',
    kind: 'normal',
    targets: 3,
    keyGroups: 2,
    target: 61,
    size: 25,
    depth: 8,
  },
  {
    id: 209,
    title: ['重新认出关系', 'Woven regions · 209'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'hard',
    shape: 'six-windows',
    kind: 'normal',
    targets: 3,
    keyGroups: 2,
    target: 68,
    size: 25,
    depth: 8,
  },
  {
    id: 210,
    title: ['大盘有条理', 'Woven regions · 210'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'normal',
    shape: 'six-windows',
    kind: 'normal',
    targets: 3,
    keyGroups: 2,
    target: 61,
    size: 25,
    depth: 12,
  },
  {
    id: 211,
    title: ['先钥后共根', 'Several openings · 211'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'normal',
    shape: 'six-windows',
    kind: 'normal',
    targets: 3,
    keyGroups: 2,
    target: 66,
    size: 25,
    depth: 11,
  },
  {
    id: 212,
    title: ['先星后两钥', 'Several openings · 212'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'hard',
    shape: 'three-islands',
    kind: 'normal',
    targets: 3,
    keyGroups: 2,
    target: 70,
    size: 25,
    depth: 8,
  },
  {
    id: 213,
    title: ['两次区域展开', 'Several openings · 213'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'normal',
    shape: 'ring',
    kind: 'normal',
    targets: 3,
    keyGroups: 2,
    target: 65,
    size: 25,
    depth: 8,
  },
  {
    id: 214,
    title: ['中段换目标', 'Several openings · 214'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'hard',
    shape: 'square',
    kind: 'normal',
    targets: 3,
    keyGroups: 2,
    target: 69,
    size: 25,
    depth: 11,
  },
  {
    id: 215,
    title: ['多段但不拖长', 'Several openings · 215'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'relief',
    shape: 'square',
    kind: 'normal',
    targets: 3,
    keyGroups: 2,
    target: 66,
    size: 25,
    depth: 11,
  },
  {
    id: 216,
    title: ['解锁后的第二根', 'Several openings · 216'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'normal',
    shape: 'square',
    kind: 'normal',
    targets: 3,
    keyGroups: 2,
    target: 65,
    size: 25,
    depth: 12,
  },
  {
    id: 217,
    title: ['第一星打开全局', 'Several openings · 217'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'hard',
    shape: 'four-islands',
    kind: 'normal',
    targets: 3,
    keyGroups: 2,
    target: 69,
    size: 25,
    depth: 10,
  },
  {
    id: 218,
    title: ['两岸轮流推进', 'Several openings · 218'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'normal',
    shape: 'islands',
    kind: 'normal',
    targets: 3,
    keyGroups: 2,
    target: 67,
    size: 25,
    depth: 13,
  },
  {
    id: 219,
    title: ['外层不必全清', 'Several openings · 219'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'hard',
    shape: 'ring',
    kind: 'normal',
    targets: 3,
    keyGroups: 2,
    target: 68,
    size: 25,
    depth: 13,
  },
  {
    id: 220,
    title: ['两次星作桥', 'Several openings · 220'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'normal',
    shape: 'square',
    kind: 'normal',
    targets: 3,
    keyGroups: 2,
    target: 66,
    size: 25,
    depth: 12,
  },
  {
    id: 221,
    title: ['中段仍有假支', 'Several openings · 221'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'hard',
    shape: 'square',
    kind: 'normal',
    targets: 3,
    keyGroups: 2,
    target: 70,
    size: 25,
    depth: 8,
  },
  {
    id: 222,
    title: ['展开后仍选择', 'Several openings · 222'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'relief',
    shape: 'square',
    kind: 'normal',
    targets: 3,
    keyGroups: 2,
    target: 64,
    size: 25,
    depth: 12,
  },
  {
    id: 223,
    title: ['三段独立判断', 'Several openings · 223'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'hard',
    shape: 'six-windows',
    kind: 'normal',
    targets: 3,
    keyGroups: 2,
    target: 71,
    size: 25,
    depth: 11,
  },
  {
    id: 224,
    title: ['先普通后带锁', 'Several openings · 224'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'normal',
    shape: 'square',
    kind: 'normal',
    targets: 3,
    keyGroups: 2,
    target: 67,
    size: 25,
    depth: 13,
  },
  {
    id: 225,
    title: ['同钥不同时间受益', 'Several openings · 225'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'hard',
    shape: 'square',
    kind: 'normal',
    targets: 3,
    keyGroups: 2,
    target: 68,
    size: 25,
    depth: 13,
  },
  {
    id: 226,
    title: ['钥匙在中段会合', 'Several openings · 226'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'normal',
    shape: 'square',
    kind: 'normal',
    targets: 3,
    keyGroups: 2,
    target: 66,
    size: 25,
    depth: 11,
  },
  {
    id: 227,
    title: ['第一目标是短支', 'Several openings · 227'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'hard',
    shape: 'three-islands',
    kind: 'normal',
    targets: 3,
    keyGroups: 2,
    target: 70,
    size: 25,
    depth: 13,
  },
  {
    id: 228,
    title: ['出口方向切换', 'Several openings · 228'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'normal',
    shape: 'square',
    kind: 'normal',
    targets: 3,
    keyGroups: 2,
    target: 65,
    size: 25,
    depth: 11,
  },
  {
    id: 229,
    title: ['近端远端再近端', 'Several openings · 229'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'hard',
    shape: 'islands',
    kind: 'normal',
    targets: 3,
    keyGroups: 2,
    target: 69,
    size: 25,
    depth: 15,
  },
  {
    id: 230,
    title: ['两颗星后再判断', 'Several openings · 230'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'normal',
    shape: 'square',
    kind: 'normal',
    targets: 3,
    keyGroups: 2,
    target: 67,
    size: 25,
    depth: 11,
  },
  {
    id: 231,
    title: ['顺畅的三段', 'Several openings · 231'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'relief',
    shape: 'square',
    kind: 'normal',
    targets: 3,
    keyGroups: 2,
    target: 64,
    size: 25,
    depth: 12,
  },
  {
    id: 232,
    title: ['合法出口会变多', 'Several openings · 232'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'hard',
    shape: 'square',
    kind: 'normal',
    targets: 3,
    keyGroups: 2,
    target: 69,
    size: 25,
    depth: 12,
  },
  {
    id: 233,
    title: ['钥匙最后才需要', 'Several openings · 233'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'normal',
    shape: 'wings',
    kind: 'normal',
    targets: 3,
    keyGroups: 2,
    target: 67,
    size: 25,
    depth: 14,
  },
  {
    id: 234,
    title: ['从共享到私有', 'Several openings · 234'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'hard',
    shape: 'square',
    kind: 'normal',
    targets: 3,
    keyGroups: 2,
    target: 68,
    size: 25,
    depth: 12,
  },
  {
    id: 235,
    title: ['从私有到共享', 'Several openings · 235'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'normal',
    shape: 'square',
    kind: 'normal',
    targets: 3,
    keyGroups: 2,
    target: 66,
    size: 25,
    depth: 9,
  },
  {
    id: 236,
    title: ['两种展开同场', 'Several openings · 236'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'hard',
    shape: 'four-islands',
    kind: 'normal',
    targets: 3,
    keyGroups: 2,
    target: 70,
    size: 25,
    depth: 14,
  },
  {
    id: 237,
    title: ['展开后快收束', 'Several openings · 237'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'relief',
    shape: 'square',
    kind: 'normal',
    targets: 3,
    keyGroups: 2,
    target: 64,
    size: 25,
    depth: 14,
  },
  {
    id: 238,
    title: ['一直留着的外翼', 'Several openings · 238'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'normal',
    shape: 'six-windows',
    kind: 'normal',
    targets: 3,
    keyGroups: 2,
    target: 66,
    size: 25,
    depth: 9,
  },
  {
    id: 239,
    title: ['多段整理解', 'Several openings · 239'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'hard',
    shape: 'square',
    kind: 'normal',
    targets: 3,
    keyGroups: 2,
    target: 72,
    size: 25,
    depth: 13,
  },
  {
    id: 240,
    title: ['完整地解开', 'Several openings · 240'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'normal',
    shape: 'six-windows',
    kind: 'normal',
    targets: 3,
    keyGroups: 2,
    target: 65,
    size: 25,
    depth: 11,
  },
  {
    id: 241,
    title: ['每支都问为什么', 'Moves that matter · 241'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'normal',
    shape: 'square',
    kind: 'normal',
    targets: 3,
    keyGroups: 2,
    target: 70,
    size: 25,
    depth: 11,
  },
  {
    id: 242,
    title: ['带锁不必清', 'Moves that matter · 242'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'hard',
    shape: 'ring',
    kind: 'normal',
    targets: 3,
    keyGroups: 2,
    target: 74,
    size: 25,
    depth: 9,
  },
  {
    id: 243,
    title: ['清爽的假入口', 'Moves that matter · 243'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'hard',
    shape: 'square',
    kind: 'normal',
    targets: 3,
    keyGroups: 2,
    target: 72,
    size: 25,
    depth: 13,
  },
  {
    id: 244,
    title: ['只借一根梁', 'Moves that matter · 244'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'normal',
    shape: 'three-islands',
    kind: 'normal',
    targets: 3,
    keyGroups: 2,
    target: 70,
    size: 25,
    depth: 11,
  },
  {
    id: 245,
    title: ['两星完成别顺手', 'Moves that matter · 245'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'hard',
    shape: 'square',
    kind: 'normal',
    targets: 3,
    keyGroups: 2,
    target: 74,
    size: 25,
    depth: 12,
  },
  {
    id: 246,
    title: ['留一点探索空间', 'Moves that matter · 246'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'relief',
    shape: 'square',
    kind: 'normal',
    targets: 3,
    keyGroups: 2,
    target: 68,
    size: 25,
    depth: 13,
  },
  {
    id: 247,
    title: ['私有支有边界', 'Moves that matter · 247'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'normal',
    shape: 'square',
    kind: 'normal',
    targets: 3,
    keyGroups: 2,
    target: 70,
    size: 25,
    depth: 11,
  },
  {
    id: 248,
    title: ['共享不用做两次', 'Moves that matter · 248'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'hard',
    shape: 'square',
    kind: 'normal',
    targets: 3,
    keyGroups: 2,
    target: 74,
    size: 25,
    depth: 9,
  },
  {
    id: 249,
    title: ['同方向不同价值', 'Moves that matter · 249'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'normal',
    shape: 'square',
    kind: 'normal',
    targets: 3,
    keyGroups: 2,
    target: 69,
    size: 25,
    depth: 13,
  },
  {
    id: 250,
    title: ['第一根留着也行', 'Moves that matter · 250'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'hard',
    shape: 'ring',
    kind: 'normal',
    targets: 3,
    keyGroups: 2,
    target: 73,
    size: 25,
    depth: 10,
  },
  {
    id: 251,
    title: ['有星也先看链', 'Moves that matter · 251'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'normal',
    shape: 'square',
    kind: 'normal',
    targets: 3,
    keyGroups: 2,
    target: 71,
    size: 25,
    depth: 13,
  },
  {
    id: 252,
    title: ['宽预算同题意', 'Moves that matter · 252'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'relief',
    shape: 'three-islands',
    kind: 'normal',
    targets: 3,
    keyGroups: 2,
    target: 68,
    size: 25,
    depth: 9,
  },
  {
    id: 253,
    title: ['前半少花也没捷径', 'Moves that matter · 253'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'hard',
    shape: 'square',
    kind: 'normal',
    targets: 3,
    keyGroups: 2,
    target: 73,
    size: 25,
    depth: 13,
  },
  {
    id: 254,
    title: ['钥匙可走仍等价', 'Moves that matter · 254'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'normal',
    shape: 'square',
    kind: 'normal',
    targets: 3,
    keyGroups: 2,
    target: 71,
    size: 25,
    depth: 13,
  },
  {
    id: 255,
    title: ['只留相关收尾', 'Moves that matter · 255'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'hard',
    shape: 'four-islands',
    kind: 'normal',
    targets: 3,
    keyGroups: 2,
    target: 72,
    size: 25,
    depth: 12,
  },
  {
    id: 256,
    title: ['全共享旁的假根', 'Moves that matter · 256'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'normal',
    shape: 'square',
    kind: 'normal',
    targets: 3,
    keyGroups: 2,
    target: 70,
    size: 25,
    depth: 9,
  },
  {
    id: 257,
    title: ['两颗星共一路半', 'Moves that matter · 257'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'hard',
    shape: 'square',
    kind: 'normal',
    targets: 3,
    keyGroups: 2,
    target: 74,
    size: 25,
    depth: 11,
  },
  {
    id: 258,
    title: ['留下半盘', 'Moves that matter · 258'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'hard',
    shape: 'six-windows',
    kind: 'normal',
    targets: 3,
    keyGroups: 2,
    target: 74,
    size: 25,
    depth: 9,
  },
  {
    id: 259,
    title: ['长而必要短而无关', 'Moves that matter · 259'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'normal',
    shape: 'wings',
    kind: 'normal',
    targets: 3,
    keyGroups: 2,
    target: 70,
    size: 25,
    depth: 15,
  },
  {
    id: 260,
    title: ['三次重新筛选', 'Moves that matter · 260'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'hard',
    shape: 'square',
    kind: 'normal',
    targets: 3,
    keyGroups: 2,
    target: 74,
    size: 25,
    depth: 13,
  },
  {
    id: 261,
    title: ['三次筛选更宽松', 'Moves that matter · 261'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'relief',
    shape: 'square',
    kind: 'normal',
    targets: 3,
    keyGroups: 2,
    target: 68,
    size: 25,
    depth: 12,
  },
  {
    id: 262,
    title: ['字母外的相关性', 'Moves that matter · 262'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'normal',
    shape: 'square',
    kind: 'normal',
    targets: 3,
    keyGroups: 2,
    target: 70,
    size: 25,
    depth: 12,
  },
  {
    id: 263,
    title: ['星邻近也可留', 'Moves that matter · 263'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'hard',
    shape: 'square',
    kind: 'normal',
    targets: 3,
    keyGroups: 2,
    target: 74,
    size: 25,
    depth: 13,
  },
  {
    id: 264,
    title: ['对岸只需两根', 'Moves that matter · 264'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'normal',
    shape: 'islands',
    kind: 'normal',
    targets: 3,
    keyGroups: 2,
    target: 69,
    size: 25,
    depth: 12,
  },
  {
    id: 265,
    title: ['开门不是任务结束', 'Moves that matter · 265'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'hard',
    shape: 'ring',
    kind: 'normal',
    targets: 3,
    keyGroups: 2,
    target: 73,
    size: 25,
    depth: 11,
  },
  {
    id: 266,
    title: ['先完成哪颗都可', 'Moves that matter · 266'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'normal',
    shape: 'wings',
    kind: 'normal',
    targets: 3,
    keyGroups: 2,
    target: 71,
    size: 25,
    depth: 11,
  },
  {
    id: 267,
    title: ['精解后的从容', 'Moves that matter · 267'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'relief',
    shape: 'square',
    kind: 'normal',
    targets: 3,
    keyGroups: 2,
    target: 68,
    size: 25,
    depth: 10,
  },
  {
    id: 268,
    title: ['少一步都不行', 'Moves that matter · 268'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'hard',
    shape: 'square',
    kind: 'normal',
    targets: 3,
    keyGroups: 2,
    target: 73,
    size: 25,
    depth: 14,
  },
  {
    id: 269,
    title: ['目标集合总检查', 'Moves that matter · 269'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'hard',
    shape: 'six-windows',
    kind: 'normal',
    targets: 3,
    keyGroups: 2,
    target: 76,
    size: 25,
    depth: 12,
  },
  {
    id: 270,
    title: ['清楚地选择', 'Moves that matter · 270'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'normal',
    shape: 'six-windows',
    kind: 'normal',
    targets: 3,
    keyGroups: 2,
    target: 69,
    size: 25,
    depth: 13,
  },
  {
    id: 271,
    title: ['大盘双根', 'Bring it together · 271'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'normal',
    shape: 'square',
    kind: 'normal',
    targets: 3,
    keyGroups: 2,
    target: 74,
    size: 25,
    depth: 13,
  },
  {
    id: 272,
    title: ['三岸交叠权限', 'Bring it together · 272'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'hard',
    shape: 'three-islands',
    kind: 'normal',
    targets: 3,
    keyGroups: 2,
    target: 78,
    size: 25,
    depth: 11,
  },
  {
    id: 273,
    title: ['一星展开两阶段', 'Bring it together · 273'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'hard',
    shape: 'square',
    kind: 'normal',
    targets: 3,
    keyGroups: 2,
    target: 76,
    size: 25,
    depth: 12,
  },
  {
    id: 274,
    title: ['大盘也能顺畅', 'Bring it together · 274'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'relief',
    shape: 'six-windows',
    kind: 'normal',
    targets: 3,
    keyGroups: 2,
    target: 73,
    size: 25,
    depth: 14,
  },
  {
    id: 275,
    title: ['两个偏心关口', 'Bring it together · 275'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'normal',
    shape: 'ring',
    kind: 'normal',
    targets: 3,
    keyGroups: 2,
    target: 75,
    size: 25,
    depth: 9,
  },
  {
    id: 276,
    title: ['先回溯第三星', 'Bring it together · 276'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'hard',
    shape: 'square',
    kind: 'normal',
    targets: 3,
    keyGroups: 2,
    target: 76,
    size: 25,
    depth: 11,
  },
  {
    id: 277,
    title: ['相似入口不同职责', 'Bring it together · 277'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'normal',
    shape: 'square',
    kind: 'normal',
    targets: 3,
    keyGroups: 2,
    target: 74,
    size: 25,
    depth: 13,
  },
  {
    id: 278,
    title: ['双钥分段再会合', 'Bring it together · 278'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'hard',
    shape: 'square',
    kind: 'normal',
    targets: 3,
    keyGroups: 2,
    target: 78,
    size: 25,
    depth: 11,
  },
  {
    id: 279,
    title: ['长线里的三种角色', 'Bring it together · 279'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'normal',
    shape: 'six-windows',
    kind: 'mixed',
    targets: 3,
    keyGroups: 2,
    target: 73,
    size: 25,
    depth: 13,
  },
  {
    id: 280,
    title: ['四区只借两区', 'Bring it together · 280'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'hard',
    shape: 'islands',
    kind: 'normal',
    targets: 3,
    keyGroups: 2,
    target: 77,
    size: 25,
    depth: 14,
  },
  {
    id: 281,
    title: ['共享的共享', 'Bring it together · 281'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'hard',
    shape: 'square',
    kind: 'normal',
    targets: 3,
    keyGroups: 2,
    target: 78,
    size: 25,
    depth: 12,
  },
  {
    id: 282,
    title: ['层次清楚地展开', 'Bring it together · 282'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'relief',
    shape: 'square',
    kind: 'normal',
    targets: 3,
    keyGroups: 2,
    target: 72,
    size: 25,
    depth: 9,
  },
  {
    id: 283,
    title: ['无锁星与双锁前置', 'Bring it together · 283'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'normal',
    shape: 'three-islands',
    kind: 'normal',
    targets: 3,
    keyGroups: 2,
    target: 74,
    size: 25,
    depth: 11,
  },
  {
    id: 284,
    title: ['不沿外圈走', 'Bring it together · 284'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'hard',
    shape: 'ring',
    kind: 'normal',
    targets: 3,
    keyGroups: 2,
    target: 78,
    size: 25,
    depth: 9,
  },
  {
    id: 285,
    title: ['先星后门再星', 'Bring it together · 285'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'normal',
    shape: 'islands',
    kind: 'normal',
    targets: 3,
    keyGroups: 2,
    target: 73,
    size: 25,
    depth: 14,
  },
  {
    id: 286,
    title: ['全共享与三对共享', 'Bring it together · 286'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'hard',
    shape: 'six-windows',
    kind: 'normal',
    targets: 3,
    keyGroups: 2,
    target: 77,
    size: 25,
    depth: 11,
  },
  {
    id: 287,
    title: ['两条合法计划', 'Bring it together · 287'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'normal',
    shape: 'square',
    kind: 'normal',
    targets: 3,
    keyGroups: 2,
    target: 75,
    size: 25,
    depth: 9,
  },
  {
    id: 288,
    title: ['第二阶段的假根', 'Bring it together · 288'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'hard',
    shape: 'ring',
    kind: 'normal',
    targets: 3,
    keyGroups: 2,
    target: 76,
    size: 25,
    depth: 14,
  },
  {
    id: 289,
    title: ['两钥相继在远端', 'Bring it together · 289'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'hard',
    shape: 'three-islands',
    kind: 'normal',
    targets: 3,
    keyGroups: 2,
    target: 77,
    size: 25,
    depth: 10,
  },
  {
    id: 290,
    title: ['熟练地读大盘', 'Bring it together · 290'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'relief',
    shape: 'six-windows',
    kind: 'normal',
    targets: 3,
    keyGroups: 2,
    target: 74,
    size: 25,
    depth: 16,
  },
  {
    id: 291,
    title: ['三个突破点', 'Bring it together · 291'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'hard',
    shape: 'six-windows',
    kind: 'normal',
    targets: 3,
    keyGroups: 2,
    target: 78,
    size: 25,
    depth: 15,
  },
  {
    id: 292,
    title: ['三星互为前置', 'Bring it together · 292'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'hard',
    shape: 'ring',
    kind: 'normal',
    targets: 3,
    keyGroups: 2,
    target: 77,
    size: 25,
    depth: 15,
  },
  {
    id: 293,
    title: ['大片可留的终局', 'Bring it together · 293'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'normal',
    shape: 'three-islands',
    kind: 'normal',
    targets: 3,
    keyGroups: 2,
    target: 75,
    size: 25,
    depth: 10,
  },
  {
    id: 294,
    title: ['权限几何双核对', 'Bring it together · 294'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'hard',
    shape: 'six-windows',
    kind: 'normal',
    targets: 3,
    keyGroups: 2,
    target: 76,
    size: 25,
    depth: 13,
  },
  {
    id: 295,
    title: ['最后一星还要想', 'Bring it together · 295'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'hard',
    shape: 'square',
    kind: 'normal',
    targets: 3,
    keyGroups: 2,
    target: 77,
    size: 25,
    depth: 9,
  },
  {
    id: 296,
    title: ['最后一段从容', 'Bring it together · 296'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'relief',
    shape: 'square',
    kind: 'normal',
    targets: 3,
    keyGroups: 2,
    target: 74,
    size: 25,
    depth: 14,
  },
  {
    id: 297,
    title: ['看穿非对称', 'Bring it together · 297'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'hard',
    shape: 'six-windows',
    kind: 'normal',
    targets: 3,
    keyGroups: 2,
    target: 76,
    size: 25,
    depth: 10,
  },
  {
    id: 298,
    title: ['自己分解全局', 'Bring it together · 298'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'hard',
    shape: 'six-windows',
    kind: 'normal',
    targets: 3,
    keyGroups: 2,
    target: 79,
    size: 25,
    depth: 12,
  },
  {
    id: 299,
    title: ['连贯的完成', 'Bring it together · 299'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'normal',
    shape: 'three-islands',
    kind: 'normal',
    targets: 3,
    keyGroups: 2,
    target: 75,
    size: 25,
    depth: 10,
  },
  {
    id: 300,
    title: ['三百关的答案', 'Bring it together · 300'],
    focus: [
      '沿星标出口追踪阻挡；普通箭头可以留下。',
      'Trace the starred exits. Ordinary arrows may stay.',
    ],
    tier: 'hard',
    shape: 'ring',
    kind: 'normal',
    targets: 3,
    keyGroups: 2,
    target: 78,
    size: 25,
    depth: 10,
  },
];
