export type ChallengeBrief = {
  id: number;
  size: number;
  target: number;
  shape: string;
  kind: 'tutorial' | 'weave' | 'long' | 'keys' | 'rush' | 'relief' | 'rescue';
  tier: 'tutorial' | 'normal' | 'relief' | 'hard';
  depth: number;
  keyGroups?: number;
  staged?: boolean;
  targets?: number;
  slack?: number;
  crossGap?: boolean;
  title: [string, string];
  focus: [string, string];
};

// These are authored candidate briefs, not a universal difficulty formula.
// Page boundaries are deliberately independent of the challenge/relief sequence.
export const challengeBriefs: ChallengeBrief[] = [
  {
    id: 1,
    size: 7,
    target: 5,
    shape: 'square',
    kind: 'tutorial',
    tier: 'tutorial',
    depth: 3,
    title: ['初见出口', 'First Exit'],
    focus: [
      '从箭头尖端沿直线看向边界。',
      'Trace a straight line from each arrowhead to the edge.',
    ],
  },
  {
    id: 2,
    size: 7,
    target: 7,
    shape: 'square',
    kind: 'tutorial',
    tier: 'tutorial',
    depth: 4,
    title: ['顺藤摸瓜', 'Follow the Trail'],
    focus: [
      '被挡住时，先看看挡路的箭头能否离开。',
      'When an exit is blocked, inspect the arrow in its way.',
    ],
  },
  {
    id: 3,
    size: 7,
    target: 9,
    shape: 'square',
    kind: 'tutorial',
    tier: 'tutorial',
    depth: 5,
    title: ['一箭多解', 'One Opens Many'],
    focus: [
      '找出同时挡住几条路线的箭头。',
      'Look for an arrow blocking several exit routes.',
    ],
  },
  {
    id: 4,
    size: 11,
    target: 18,
    shape: 'diamond',
    kind: 'rescue',
    tier: 'normal',
    depth: 6,
    targets: 1,
    slack: 4,
    title: ['只为这颗星', 'Follow the Star'],
    focus: [
      '在步数内送走星标箭头；普通箭头不必全部清空。',
      'Free the starred arrow within the move budget. Other arrows may stay.',
    ],
  },
  {
    id: 5,
    size: 13,
    target: 22,
    shape: 'cross',
    kind: 'rescue',
    tier: 'normal',
    depth: 7,
    targets: 1,
    slack: 2,
    title: ['有所取舍', 'Choose What Matters'],
    focus: [
      '先追踪星标的阻挡，把步数留给相关的箭头。',
      'Trace the star’s blockers and spend moves on the arrows that matter.',
    ],
  },
  {
    id: 6,
    size: 11,
    target: 18,
    shape: 'hourglass',
    kind: 'relief',
    tier: 'relief',
    depth: 5,
    title: ['顺势而下', 'An Easy Current'],
    focus: [
      '这一关清空全部箭头，顺着打开的通路继续。',
      'Clear every arrow and follow the openings as they appear.',
    ],
  },
  {
    id: 7,
    size: 13,
    target: 24,
    shape: 'wings',
    kind: 'rescue',
    tier: 'normal',
    depth: 7,
    targets: 2,
    slack: 3,
    title: ['两星同路', 'Two Stars Together'],
    focus: [
      '两颗星可能共享挡路的箭头，先看清它们的联系。',
      'Two stars may share blockers. Look for their connection.',
    ],
  },
  {
    id: 8,
    crossGap: true,
    size: 15,
    target: 30,
    shape: 'ring',
    kind: 'rescue',
    tier: 'hard',
    depth: 8,
    targets: 2,
    slack: 1,
    title: ['环中的突破', 'The Opening in the Ring'],
    focus: [
      '星标的出口穿过留白；别把步数花在无关支路上。',
      'Trace the stars’ exits across the gap and leave unrelated branches alone.',
    ],
  },
  {
    id: 9,
    size: 11,
    target: 14,
    shape: 'diamond',
    kind: 'relief',
    tier: 'relief',
    depth: 4,
    title: ['轻轻一过', 'A Little Breather'],
    focus: [
      '没有步数限制，清空这张小图。',
      'No move limit here. Clear this small board.',
    ],
  },
  {
    id: 10,
    size: 15,
    target: 18,
    shape: 'ring',
    kind: 'long',
    tier: 'normal',
    depth: 7,
    title: ['长线初探', 'Long Ribbons'],
    focus: [
      '线身可以拐弯，离场方向始终由尖端决定。',
      'Bodies can bend; the arrowhead determines the straight exit.',
    ],
  },
  {
    id: 11,
    size: 13,
    target: 24,
    shape: 'cross',
    kind: 'keys',
    tier: 'normal',
    depth: 7,
    keyGroups: 1,
    title: ['第一把钥匙', 'The First Key'],
    focus: [
      '移走钥匙 A 打开同字母的锁；解锁后仍需通路畅通。',
      'Remove key A to open matching locks; each exit must still be clear.',
    ],
  },
  {
    id: 12,
    size: 15,
    target: 28,
    shape: 'wings',
    kind: 'rescue',
    tier: 'normal',
    depth: 8,
    keyGroups: 1,
    targets: 1,
    slack: 3,
    title: ['星光在门后', 'A Star Behind the Gate'],
    focus: [
      '星标在钥门之后，先找到它需要的钥匙和通路。',
      'Find the key and clear the route to the star behind its gate.',
    ],
  },
  {
    id: 13,
    size: 15,
    target: 32,
    shape: 'diamond',
    kind: 'rescue',
    tier: 'hard',
    depth: 8,
    keyGroups: 1,
    targets: 2,
    slack: 1,
    title: ['一钥双星', 'One Key, Two Stars'],
    focus: [
      '同时照顾两颗星，留意它们共同需要的箭头。',
      'Plan for both stars and look for arrows they both need.',
    ],
  },
  {
    id: 14,
    size: 11,
    target: 16,
    shape: 'hourglass',
    kind: 'relief',
    tier: 'relief',
    depth: 4,
    title: ['小小歇脚', 'A Quiet Pause'],
    focus: [
      '清空全部箭头，轻松重温已经学会的观察方法。',
      'Clear every arrow using the patterns you already know.',
    ],
  },
  {
    id: 15,
    crossGap: true,
    size: 15,
    target: 26,
    shape: 'islands',
    kind: 'rescue',
    tier: 'normal',
    depth: 7,
    targets: 2,
    slack: 2,
    title: ['隔岸星光', 'Stars Across the Water'],
    focus: [
      '隔着留白也会阻挡；从两颗星追到远处的线索。',
      'Blockers can sit across the gap. Trace both stars to their distant clues.',
    ],
  },
  {
    id: 16,
    size: 17,
    target: 20,
    shape: 'diamond',
    kind: 'long',
    tier: 'normal',
    depth: 8,
    targets: 1,
    slack: 2,
    title: ['长线寻星', 'A Star Among Ribbons'],
    focus: [
      '先认星标尖端，再沿离场直线检查长长的线身。',
      'Find the starred head, then check the long bodies along its exit ray.',
    ],
  },
  {
    id: 17,
    size: 17,
    target: 34,
    shape: 'wings',
    kind: 'keys',
    tier: 'normal',
    depth: 9,
    keyGroups: 2,
    title: ['双钥展开', 'Two Keys Unfold'],
    focus: [
      '分别找到 A、B 两把钥匙，再清空两组路线。',
      'Find keys A and B, then clear the routes in both groups.',
    ],
  },
  {
    id: 18,
    size: 17,
    target: 40,
    shape: 'cross',
    kind: 'rush',
    tier: 'normal',
    depth: 9,
    title: ['一片打开', 'Wide Open'],
    focus: [
      '这一关清空全部箭头，享受通路连续展开。',
      'Clear every arrow and follow the opening branches.',
    ],
  },
  {
    id: 19,
    size: 17,
    target: 32,
    shape: 'hourglass',
    kind: 'rescue',
    tier: 'normal',
    depth: 8,
    keyGroups: 2,
    targets: 2,
    slack: 2,
    title: ['钥匙的去向', 'Where the Keys Lead'],
    focus: [
      '看清星标需要哪组钥门，再决定从哪里开始。',
      'Read which gates the stars need before choosing an opening.',
    ],
  },
  {
    id: 20,
    size: 17,
    target: 36,
    shape: 'diamond',
    kind: 'rescue',
    tier: 'hard',
    depth: 10,
    keyGroups: 2,
    staged: true,
    targets: 3,
    slack: 1,
    title: ['三星接力', 'Three-Star Relay'],
    focus: [
      'A 打开 B 的下一段路；把三颗星的线索连起来。',
      'A opens the next stage toward B. Connect the clues for all three stars.',
    ],
  },
  {
    id: 21,
    size: 13,
    target: 18,
    shape: 'cross',
    kind: 'relief',
    tier: 'relief',
    depth: 5,
    title: ['轻装再行', 'Travel Light'],
    focus: [
      '回到小图，清空全部箭头。',
      'Return to a small board and clear every arrow.',
    ],
  },
  {
    id: 22,
    crossGap: true,
    size: 19,
    target: 24,
    shape: 'ring',
    kind: 'long',
    tier: 'normal',
    depth: 8,
    targets: 2,
    slack: 2,
    title: ['回环双星', 'Two Stars in the Ring'],
    focus: [
      '顺着星标的出口，寻找空心另一侧的阻挡。',
      'Follow a starred exit across the empty center to its blocker.',
    ],
  },
  {
    id: 23,
    size: 17,
    target: 34,
    shape: 'wings',
    kind: 'rescue',
    tier: 'normal',
    depth: 9,
    keyGroups: 2,
    staged: true,
    targets: 2,
    slack: 2,
    title: ['门后的联系', 'Beyond the Gates'],
    focus: [
      '先读清钥匙接力，再追踪两颗星的共同阻挡。',
      'Read the key relay, then trace the blockers shared by both stars.',
    ],
  },
  {
    id: 24,
    size: 17,
    target: 42,
    shape: 'hourglass',
    kind: 'rush',
    tier: 'normal',
    depth: 10,
    title: ['流光清场', 'A Flow of Arrows'],
    focus: [
      '没有步数限制，沿新打开的分支连续清场。',
      'No move limit. Follow newly opened branches to clear the board.',
    ],
  },
  {
    id: 25,
    size: 17,
    target: 36,
    shape: 'islands',
    kind: 'rescue',
    tier: 'normal',
    depth: 9,
    targets: 3,
    slack: 2,
    title: ['三星相望', 'Three Distant Stars'],
    focus: [
      '不需要钥匙；看清哪些支路与三颗星有关。',
      'No keys this time. Find the branches needed by the three stars.',
    ],
  },
  {
    id: 26,
    size: 19,
    target: 40,
    shape: 'diamond',
    kind: 'rescue',
    tier: 'hard',
    depth: 10,
    keyGroups: 2,
    staged: true,
    targets: 3,
    slack: 1,
    title: ['层层星门', 'Layers of Starlight'],
    focus: [
      '把目标、钥匙和阻挡串起来，少走无关的一步。',
      'Connect targets, keys and blockers, saving moves for what matters.',
    ],
  },
  {
    id: 27,
    size: 13,
    target: 20,
    shape: 'diamond',
    kind: 'relief',
    tier: 'relief',
    depth: 5,
    title: ['星海小憩', 'A Gentle Interlude'],
    focus: [
      '清空全部箭头，让熟悉的关系变成顺畅的动作。',
      'Clear every arrow and turn familiar patterns into fluent moves.',
    ],
  },
  {
    id: 28,
    size: 19,
    target: 26,
    shape: 'ring',
    kind: 'long',
    tier: 'normal',
    depth: 9,
    targets: 2,
    slack: 2,
    title: ['长卷双星', 'Stars in a Long Scroll'],
    focus: [
      '长线并不都需要移走，只处理挡住星标的部分。',
      'Not every ribbon needs to leave. Follow the ones blocking the stars.',
    ],
  },
  {
    id: 29,
    size: 19,
    target: 42,
    shape: 'cross',
    kind: 'rescue',
    tier: 'normal',
    depth: 10,
    keyGroups: 2,
    staged: true,
    targets: 3,
    slack: 2,
    title: ['最后的铺垫', 'One More Connection'],
    focus: [
      '在三颗星之间切换观察，找到共同需要的钥匙和箭头。',
      'Compare all three stars and find the keys and arrows they share.',
    ],
  },
  {
    id: 30,
    size: 19,
    target: 46,
    shape: 'wings',
    kind: 'rescue',
    tier: 'hard',
    depth: 11,
    keyGroups: 2,
    staged: true,
    targets: 3,
    slack: 1,
    title: ['星途终章', 'The Starward Finale'],
    focus: [
      '用已经掌握的关系，在步数内送走最后三颗星。',
      'Use the patterns you have learned to free the final three stars within the budget.',
    ],
  },
];
